version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: one-not
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  server:
    image: yourdockerhubusername/one-not-server:latest
    depends_on: [postgres, redis]
    env_file: .env.prod
    ports: ["4000:4000"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  web:
    image: yourdockerhubusername/one-not-web:latest
    depends_on: [server]
    env_file: .env.prod
    ports: ["3000:3000"]
    restart: unless-stopped

volumes:
  pgdata:
