services:
  - type: web
    name: one-not-server
    env: docker
    rootDir: apps/server
  - type: web
    name: one-not-web
    env: docker
    rootDir: apps/web
  - type: redis
    name: one-not-redis

databases:
  - name: one-not-db