name: Deploy One-Not App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/one-not-server:latest

      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/one-not-web:latest
